package genres

var All = []string{
	"acid rock",
	"alternative metal",
	"alternative punk",
	"alternative rock",
	"anarcho-punk",
	"anatolian rock",
	"aor",
	"art punk",
	"art rock",
	"asian rock",
	"atmospheric black metal",
	"atmospheric sludge metal",
	"avant-garde metal",
	"beat rock",
	"beatdown hardcore",
	"birmingham sound",
	"black 'n' roll",
	"black metal",
	"blackened crust",
	"blackened death metal",
	"blackgaze",
	"blues rock",
	"boogie rock",
	"britpop",
	"british folk rock",
	"brutal death metal",
	"burning spirits",
	"celtic metal",
	"celtic punk",
	"celtic rock",
	"christian hardcore",
	"christian metal",
	"christian rock",
	"classic rock",
	"coldwave",
	"crack rock steady",
	"crossover thrash",
	"crust punk",
	"cyber metal",
	"d-beat",
	"dance-punk",
	"dance-rock",
	"dark wave",
	"death 'n' roll",
	"death metal",
	"death-doom metal",
	"deathcore",
	"deathgrind",
	"deathrock",
	"depressive black metal",
	"desert rock",
	"digital hardcore",
	"dissonant black metal",
	"dissonant death metal",
	"djent",
	"doom metal",
	"doomcore",
	"doomgaze",
	"dream pop",
	"drone metal",
	"easycore",
	"electronic rock",
	"electronicore",
	"electropunk",
	"emo",
	"emo pop",
	"emo rap",
	"emocore",
	"emoviolence",
	"epic doom metal",
	"experimental rock",
	"folk metal",
	"folk punk",
	"folk rock",
	"funeral doom metal",
	"funk metal",
	"funk rock",
	"garage punk",
	"garage rock",
	"garage rock revival",
	"geek rock",
	"glam metal",
	"glam punk",
	"glam rock",
	"goregrind",
	"gothic",
	"gothic metal",
	"gothic rock",
	"grebo",
	"grindcore",
	"groove metal",
	"grunge",
	"gypsy punk",
	"hard rock",
	"hardcore hip hop",
	"hardcore punk",
	"hardwave",
	"heartland rock",
	"heavy metal",
	"heavy psych",
	"horror punk",
	"indie",
	"indie folk",
	"indie pop",
	"indie rock",
	"indie surf",
	"indietronica",
	"industrial",
	"industrial hardcore",
	"industrial hip hop",
	"industrial metal",
	"industrial rock",
	"j-rock",
	"krautrock",
	"machine rock",
	"madchester",
	"mainstream rock",
	"math pop",
	"math rock",
	"mathcore",
	"medieval metal",
	"medieval rock",
	"melodic black metal",
	"melodic death metal",
	"melodic hardcore",
	"melodic metalcore",
	"metal",
	"metalcore",
	"midwest emo",
	"minneapolis sound",
	"neoclassical metal",
	"neocrust",
	"neo-progressive rock",
	"neo-psychedelia",
	"neue deutsche härte",
	"new wave",
	"nintendocore",
	"no wave",
	"noise pop",
	"noise rock",
	"nu metal",
	"nwobhm",
	"occult rock",
	"oi",
	"old school death metal",
	"pagan black metal",
	"paisley underground",
	"piano rock",
	"pop metal",
	"pop punk",
	"pop screamo",
	"post-britpop",
	"post-grunge",
	"post-hardcore",
	"post-metal",
	"post-punk",
	"post-punk revival",
	"post-rock",
	"power metal",
	"powerviolence",
	"progressive",
	"progressive metal",
	"progressive metalcore",
	"progressive rock",
	"proto-punk",
	"psychedelic",
	"psychedelic rock",
	"psychobilly",
	"pub rock",
	"punk",
	"punk blues",
	"punk rap",
	"punk rock",
	"rap metal",
	"rap rock",
	"rapcore",
	"raw punk",
	"riot grrrl",
	"rock",
	"rock and roll",
	"rock opera",
	"roots rock",
	"screamo",
	"shitgaze",
	"shoegaze",
	"ska punk",
	"skacore",
	"skate punk",
	"slam death metal",
	"slacker rock",
	"sleaze rock",
	"slowcore",
	"sludge metal",
	"southern metal",
	"southern rock",
	"space rock",
	"speed metal",
	"stoner metal",
	"stoner rap",
	"stoner rock",
	"street punk",
	"surf punk",
	"surf rock",
	"swancore",
	"symphonic black metal",
	"symphonic metal",
	"symphonic rock",
	"technical death metal",
	"technical thrash metal",
	"thall",
	"thrash metal",
	"thrashcore",
	"traditional doom metal",
	"trance metal",
	"trap metal",
	"uk82",
	"viking metal",
	"viking rock",
	"visual kei",
	"war metal",
}