---
name: Daily Music Release Publisher

on:
  schedule:
    - cron: "0 0 * * *" # 00:00 UTC daily
  workflow_dispatch: {}

jobs:
  publish:
    name: Publish
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: "go.mod"
          cache: "true"
          cache-dependency-path: "go.sum"

      - name: Run
        env:
          RELEASE_PROVIDER: "${{ vars.RELEASE_PROVIDER }}"
          GEMINI_API_KEY: "${{ secrets.GEMINI_API_KEY }}"
          DISCORD_WEBHOOK_URL: "${{ secrets.DISCORD_WEBHOOK_URL }}"
          TELEGRAM_BOT_TOKEN: "${{ secrets.TELEGRAM_BOT_TOKEN }}"
          TELEGRAM_CHAT_ID: "${{ secrets.TELEGRAM_CHAT_ID }}"
          THREADS_CLIENT_ID: "${{ secrets.THREADS_CLIENT_ID }}"
          THREADS_CLIENT_SECRET: "${{ secrets.THREADS_CLIENT_SECRET }}"
          THREADS_REDIRECT_URI: "${{ secrets.THREADS_REDIRECT_URI }}"
          THREADS_ACCESS_TOKEN: "${{ secrets.THREADS_ACCESS_TOKEN }}"
        run: make run
