---
name: Linting

on: # yamllint disable-line rule:truthy
  pull_request: {}
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      linter:
        description: "Run this linter:"
        required: false
        default: all
        type: choice
        options: [all, pre-commit, go-lint]

permissions:
  contents: read

jobs:
  go-lint:
    name: Go Lint
    if: contains(fromJSON('["all", "go-lint"]'), github.event.inputs.linter || 'all')
    uses: fabasoad/reusable-workflows/.github/workflows/wf-go-lint.yml@eugene/b27c5c1c

  pre-commit:
    name: Pre-commit
    if: contains(fromJSON('["all", "pre-commit"]'), github.event.inputs.linter || 'all')
    uses: fabasoad/reusable-workflows/.github/workflows/wf-pre-commit.yml@main
    with:
      skip-hooks: "audit, test"
